# Generated by Django 3.0.7 on 2020-06-18 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('teaching_since', models.DateField(null=True)),
                ('instrument', models.CharField(max_length=100, null=True)),
                ('teacher_type', models.CharField(choices=[('administrator', 'administrator'), ('assistant', 'assistant'), ('regularteacher', 'regularteacher')], default='administrator', max_length=20)),
                ('email', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('skill_level', models.CharField(max_length=100, null=True)),
                ('instrument', models.CharField(max_length=100, null=True)),
                ('student_since', models.DateField(null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('birthday', models.CharField(max_length=100, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='school', to='school.School')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='teacher', to='school.Teacher')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
