# Generated by Django 3.0.7 on 2020-06-18 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_student_teacher'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='school',
            table=None,
        ),
    ]
