# Generated by Django 3.0.7 on 2020-06-18 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20200618_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='school', to='school.School'),
        ),
        migrations.AlterField(
            model_name='student',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='teacher', to='school.Teacher'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'student'), ('teacher', 'teacher')], max_length=10),
        ),
    ]
